"""add_ai_usage_table

Revision ID: bb3aea586917
Revises: 4c005bb76409
Create Date: 2026-01-24 03:59:19.352812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb3aea586917"
down_revision: Union[str, Sequence[str], None] = "4c005bb76409"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("operation", sa.String(length=50), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_dollars", sa.Float(), nullable=True),
        sa.Column("generation_id", sa.String(length=100), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_ai_usage_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_usage")),
    )
    op.create_index(op.f("ix_ai_usage_created_at"), "ai_usage", ["created_at"], unique=False)
    op.create_index(op.f("ix_ai_usage_operation"), "ai_usage", ["operation"], unique=False)
    op.create_index(op.f("ix_ai_usage_user_id"), "ai_usage", ["user_id"], unique=False)
    op.drop_index("ix_username", table_name="admins")
    op.drop_constraint("uq_admins_username", "admins", type_="unique")
    op.create_index(op.f("ix_admins_username"), "admins", ["username"], unique=True)
    op.drop_index("ix_horoscope_cache_date", table_name="horoscope_cache")
    op.create_index(
        op.f("ix_horoscope_cache_horoscope_date"),
        "horoscope_cache",
        ["horoscope_date"],
        unique=False,
    )
    op.drop_index("ix_zodiac_sign", table_name="horoscope_content")
    op.drop_constraint("uq_horoscope_content_zodiac_sign", "horoscope_content", type_="unique")
    op.create_index(
        op.f("ix_horoscope_content_zodiac_sign"), "horoscope_content", ["zodiac_sign"], unique=True
    )
    op.drop_constraint("image_assets_asset_key_key", "image_assets", type_="unique")
    op.drop_index("ix_image_assets_asset_key", table_name="image_assets")
    op.create_index(op.f("ix_image_assets_asset_key"), "image_assets", ["asset_key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_image_assets_asset_key"), table_name="image_assets")
    op.create_index("ix_image_assets_asset_key", "image_assets", ["asset_key"], unique=False)
    op.create_unique_constraint(
        "image_assets_asset_key_key",
        "image_assets",
        ["asset_key"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_horoscope_content_zodiac_sign"), table_name="horoscope_content")
    op.create_unique_constraint(
        "uq_horoscope_content_zodiac_sign",
        "horoscope_content",
        ["zodiac_sign"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index("ix_zodiac_sign", "horoscope_content", ["zodiac_sign"], unique=False)
    op.drop_index(op.f("ix_horoscope_cache_horoscope_date"), table_name="horoscope_cache")
    op.create_index("ix_horoscope_cache_date", "horoscope_cache", ["horoscope_date"], unique=False)
    op.drop_index(op.f("ix_admins_username"), table_name="admins")
    op.create_unique_constraint(
        "uq_admins_username", "admins", ["username"], postgresql_nulls_not_distinct=False
    )
    op.create_index("ix_username", "admins", ["username"], unique=False)
    op.drop_index(op.f("ix_ai_usage_user_id"), table_name="ai_usage")
    op.drop_index(op.f("ix_ai_usage_operation"), table_name="ai_usage")
    op.drop_index(op.f("ix_ai_usage_created_at"), table_name="ai_usage")
    op.drop_table("ai_usage")
    # ### end Alembic commands ###
